services:
  user-service:
    build: ./app/user-service
    container_name: user-service
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/fintech

  transaction-service:
    build: ./app/transaction-service
    container_name: transaction-service
    ports:
      - "8082:8082"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/fintech

  history-service:
    build: ./app/history-service
    container_name: history-service
    ports:
      - "8083:8083"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/fintech

  frontend:
    build: ./app/frontend
    container_name: fintech-frontend
    ports:
      - "3000:3000"
    depends_on:
      - user-service
      - transaction-service
      - history-service

  mongo:
    image: mongo:6
    container_name: fintech-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
